### ISSUE TITLE
CompCert Test Dataset

### ISSUE THREAD

**Issue by liuxingpeng520521** [trishullab/copra#26]
How are the 118 lemmas in CompCert Test Dataset, I can't find a benchmark from your config file that contains 118 lemmas

**Comment by amit9oct** [comment]
https://github.com/trishullab/copra/blob/main/src/main/config/benchmark/compcert_118_subset.yaml

This has the theorems. It is also important to note that some theorems with identical statement are mentioned in two different environments we just prove it once. These exists from the initial proverbot set of 98 successfully proved theorems.

**Comment by liuxingpeng520521** [comment]
Thank You very much.
