### ISSUE TITLE
CompCert Test Dataset

### ISSUE THREAD

**Issue by liuxingpeng520521** [trishullab/copra#27]
Sorry，but the CompCert Test Dataset you gave was only 109 lemma.

**Comment by amit9oct** [comment]
https://github.com/trishullab/copra/issues/26

Please read the answer again. Some theorems with identical statement are proved more than once which pushes the number to 118. See the comments in the yaml.

**Comment by liuxingpeng520521** [comment]
Thank you very much.

**Comment by liuxingpeng520521** [comment]
Thank you very much.
